[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-freefont",
  "fontconfig"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node server.js"
