ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_organization VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_street VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_street2 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_state VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_zip VARCHAR(20);
